package ru.project.ticketsearchassistantbot.api;

public enum BotState {

    START_OF_TICKET_SEARCH_HANDLER("START_OF_TICKET_SEARCH_HANDLER"),
    FILLING_PROFILE_HANDLER("FILLING_PROFILE_HANDLER"),
    OUTPUT_OF_COMPLETED_DATA_HANDLER("OUTPUT_OF_COMPLETED_DATA_HANDLER"),
    SHOW_MAIN_MENU_HANDLER("SHOW_MAIN_MENU_HANDLER"),
    SHOW_FOUND_TRAINS_HANDLER("SHOW_FOUND_TRAINS_HANDLER"),
    SHOW_HELP_MENU_HANDLER("SHOW_HELP_MENU_HANDLER"),
    FILLING_IN_THE_CALENDAR_HANDLER("FILLING_IN_THE_CALENDAR_HANDLER"),

    ASK_DEPARTURE_STATION("ASK_DEPARTURE_STATION"),
    ASK_ARRIVAL_STATION("ASK_ARRIVAL_STATION"),
    ASK_DEPARTURE_DATE("ASK_DEPARTURE_DATE"),
    CALENDAR_FILLED("CALENDAR_FILLED"),

    JANUARY("JANUARY"),
    FEBRUARY("FEBRUARY"),
    MARCH("MARCH"),
    APRIL("APRIL"),
    MAY("MAY"),
    JUNE("JUNE"),
    JULY("JULY"),
    AUGUST("AUGUST"),
    SEPTEMBER("SEPTEMBER"),
    OCTOBER("OCTOBER"),
    NOVEMBER("NOVEMBER"),
    DECEMBER("DECEMBER");

    BotState(String title) {
    }
}
